ubuntu:
  build: .
  ports:
   - '8080:8080'
  environment:
    SERVER_LOG_MINIMAL: 1
    SERVER_APP_NAME: docker-test
    S6_KILL_FINISH_MAXTIME: 1
    S6_KILL_GRACETIME: 1
    SERVER_WORKER_PROCESSES: 1
    SERVER_CLIENT_HEADER_BUFFER_SIZE: 8k
    SERVER_LARGE_CLIENT_HEADER_BUFFERS: 8 16k
    SERVER_CLIENT_BODY_BUFFER_SIZE: 128k
  volumes:
   - ./container/root/tests/nginx/base.goss.yaml:/tests/nginx/base.goss.yaml
   - ./container/root/var/www/html:/var/www/html
alpine:
  build: .
  dockerfile: Dockerfile-alpine
  ports:
   - '8081:8080'
  environment:
    SERVER_LOG_MINIMAL: 1
    SERVER_APP_NAME: docker-test
    S6_KILL_FINISH_MAXTIME: 1
    S6_KILL_GRACETIME: 1
    SERVER_WORKER_PROCESSES: 1
  volumes:
   - ./container/root/tests/nginx/base.goss.yaml:/tests/nginx/base.goss.yaml
   - ./container/root/var/www/html:/var/www/html
